/**
 * Created by yeonjukko on 2016. 1. 11..
 */

const FLAG_ERROR_CODE = 1000;
const FLAG_SUCCESS_CODE = 2000;
const FLAG_SIGNUP_FAILED_CODE = 4001;
const FLAG_LOGIN_FAILED_CODE = 4002;
const FLAG_SESSION_FAILED_CODE = 4003;
const FLAG_TITLE_LOADING_FAILED_CODE = 4004;
const FLAG_MEMO_NAME_LOADING_FAILED_CODE = 4005;
const FLAG_MEMO_DATA_LOADING_FAILED_CODE = 4006;
const FLAG_MEMO_UPDATE_FAILED_CODE = 4007;

const FLAG_ERROR_MESSAGE = '알 수없는 에러 발생!';
const FLAG_SUCCESS_MESSAGE = '성공';
const FLAG_SIGNUP_FAILED_MESSAGE = '이미 가입된 회원정보입니다.';
const FLAG_LOGIN_FAILED_MESSAGE = '로그인에 실패하였습니다.';
const FLAG_SESSION_FAILED_MESSAGE = '잘못된 세션입니다.';
const FLAG_TITLE_LOADING_FAILED_MESSAGE = '타이틀을 불러오지 못하였습니다.'
const FLAG_MEMO_NAME_LOADING_FAILED_MESSAGE = '메모 이름을 불러오지 못하였습니다.'
const FLAG_MEMO_DATA_LOADING_FAILED_MESSAGE = '메모 데이터를 불러오지 못하였습니다.'
const FLAG_MEMO_UPDATE_FAILED_MESSAGE = '메모 업데이트를 실패하였습니다.'


const FLAG_ERROR_JSON = {
    "code": FLAG_ERROR_CODE,
    "msg": FLAG_ERROR_MESSAGE
};

const FLAG_SUCCESS_JSON = {
    "code": FLAG_SUCCESS_CODE,
    "msg": FLAG_SUCCESS_MESSAGE
};

const FLAG_SIGNUP_FAILED_JSON = {
    "code": FLAG_SIGNUP_FAILED_CODE,
    "msg": FLAG_SIGNUP_FAILED_MESSAGE
};

const FLAG_LOGIN_FAILED_JSON = {
    "code": FLAG_LOGIN_FAILED_CODE,
    "msg": FLAG_LOGIN_FAILED_MESSAGE
};

const FLAG_SESSION_FAILED_JSON = {
    "code": FLAG_SESSION_FAILED_CODE,
    "msg": FLAG_SESSION_FAILED_MESSAGE
};

const FLAG_TITLE_LOADING_FAILED_JSON = {
    "code": FLAG_TITLE_LOADING_FAILED_CODE,
    "msg": FLAG_TITLE_LOADING_FAILED_MESSAGE
};

const FLAG_MEMO_NAME_LOADING_FAILED_JSON = {
    "code": FLAG_MEMO_NAME_LOADING_FAILED_CODE,
    "msg": FLAG_MEMO_NAME_LOADING_FAILED_MESSAGE
};

const FLAG_MEMO_DATA_LOADING_FAILED_JSON = {
    "code": FLAG_MEMO_DATA_LOADING_FAILED_CODE,
    "msg": FLAG_MEMO_DATA_LOADING_FAILED_MESSAGE
};

const FLAG_MEMO_UPDATE_FAILED_JSON = {
    "code": FLAG_MEMO_UPDATE_FAILED_CODE,
    "msg": FLAG_MEMO_UPDATE_FAILED_MESSAGE
};

exports.FLAG_ERROR_JSON = FLAG_ERROR_JSON;
exports.FLAG_SUCCESS_JSON = FLAG_SUCCESS_JSON;
exports.FLAG_SIGNUP_FAILED_JSON = FLAG_SIGNUP_FAILED_JSON;
exports.FLAG_LOGIN_FAILED_JSON = FLAG_LOGIN_FAILED_JSON;
exports.FLAG_SESSION_FAILED_JSON = FLAG_SESSION_FAILED_JSON;
exports.FLAG_TITLE_LOADING_FAILED_JSON = FLAG_TITLE_LOADING_FAILED_JSON;
exports.FLAG_MEMO_NAME_LOADING_FAILED_JSON = FLAG_MEMO_NAME_LOADING_FAILED_JSON;
exports.FLAG_MEMO_DATA_LOADING_FAILED_JSON = FLAG_MEMO_DATA_LOADING_FAILED_JSON;
exports.FLAG_MEMO_UPDATE_FAILED_JSON = FLAG_MEMO_UPDATE_FAILED_JSON;



